# Generated by Django 4.1.5 on 2023-02-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_remove_useraddressbook_status_useraddressbook_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddressbook',
            name='address',
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='street_address',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='zipcode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
