# Generated by Django 4.1.5 on 2023-02-05 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_remove_useraddressbook_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddressbook',
            name='order',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='billing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.useraddressbook'),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='city',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
